#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#Answer: 4613732

i = 1
previ1 = 1
previ2 = 0
n = 0
while (i <= 4*10**6):
    previ2 = previ1
    previ1 = i
    if (i % 2 == 0):
        n += i
        
    i = previ1 + previ2

print (n)